# Load v4l2loopback at boot for gpwebcam. Options are in
# /usr/lib/modprobe.d/99-gpwebcam.conf. To opt out, create an empty file or
# a link to /dev/null with the same name in /etc/modules-load.d/.
v4l2loopback
